simplemooc/courses/urls.py
from django.conf.urls import  include, url
import simplemooc.courses.views

urlpatterns = [
    url(r'^$', simplemooc.courses.views.index, name='index'),
    #url(r'^(?P<pk>\d+)/$', simplemooc.courses.views.details, name='details'), # utilizará o codigo na url
    url(r'^(?P<slug>[\w_-]+)/$', simplemooc.courses.views.details, name='details'), # utlizara o slug, \w+ = 1 ou mais letras
    
    url(r'^(?P<slug>[\w_-]+)/enrollment/$', simplemooc.courses.views.enrollment, name='enrollment'),
]

simplemooc/urls.py
from django.conf.urls import include, url
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace='core')),
    url(r'^accounts/', include('simplemooc.accounts.urls', namespace='accounts')),
    url(r'^courses/', include('simplemooc.courses.urls', namespace='courses')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    #document_root=settings.MEDIA_ROOT = caminho absoluto
    #settings.MEDIA_URL = caminho relativo
    #este método funciona apenas de "debug mode"
    #indica qual é o caminho absoluto e relativo para estas midias
    #https://docs.djangoproject.com/en/dev/howto/static-files/
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/courses/models.py
# -*- coding: utf 8 -*-
from django.db import models
from django.conf import settings

# Custom manager
class CourseManager(models.Manager):
    
    # Filtro do batabase
    def search(self, query):
        return self.get_queryset().filter(
            #name__icontains=query, description__icontains=query # and
            #models.Q(name__icontains=query) & models.Q(description__icontains=query) # end
            models.Q(name__icontains=query) | models.Q(description__icontains=query) # or
        )
        
        
# https://docs.djangoproject.com/en/1.11/ref/models/instances/
class Course(models.Model):
    
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    description = models.TextField('Descricao',blank=True)
    about = models.TextField('Sobre o curso', blank=True)
    start_date = models.DateField('Data de Início', null=True, blank=True)
    image = models.ImageField(upload_to='courses/images', verbose_name='Imagem', null=True, blank=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    objects = CourseManager()
    
    # The __str__() method is called whenever you call str() on an object
    # Mostra o atributo nome do curso ao invés do objeto.
    def __str__(self):
        return self.name
        
    @models.permalink
    def get_absolute_url(self):
        #from django.core.urlresolvers import reverse # ja esta incluido
        return ('courses:details', (), ({'slug': self.slug}))
        
    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ['name'] # cres
        #ordering = ['-name'] # decres
        

class Enrollment(models.Model):
    STATUS_CHOICES = (
            (0, 'Pendente'),
            (1, 'Aprovado'),
            (2, 'Cancelado'),
        )
    
    user = models.ForeignKey(
            settings.AUTH_USER_MODEL, verbose_name='Usuário',
            related_name='enrollments'
        )
    course = models.ForeignKey(
            Course, verbose_name='Curso', related_name='enrollments'
        )
    status = models.IntegerField('Situação', choices=STATUS_CHOICES, default=1, blank=True)

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def active(self):
        self.status = 1
        self.save()
    
    class Meta:
        verbose_name = 'Inscrição'
        verbose_name_plural = 'Inscrições'
        unique_together = (('user','course'),) # Usado para indicar unicidade. Apenas poderá existir um 'Enrollment' com par user e course
                 

simplemooc/courses/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings
from simplemooc.core.mail import send_mail_template

class ContactCourse(forms.Form):
    
    name = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem/Dúvida', widget=forms.Textarea)
    
    def send_mail(self, course):
        subject = '[%s] Contato' % course
        context = {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message'],
        }
        template_name = 'courses/contact_email.html'
        send_mail_template(
            subject, template_name, context, [settings.CONTACT_EMAIL]   
        )

simplemooc/courses/views.py
# colocar na view apenas o necessário. Minimo possivel.

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Course, Enrollment
from .forms import ContactCourse # o ponto indica que o import é relatico ao proprio pacote

def index(request):
    courses = Course.objects.all() #Course=model , objects=manager do model , retorna todos os objs
    template_name = 'courses/index.html'
    context = { # dicionario que será passado para o render para subtituir valores no template
        'courses': courses,
    }
    return render(request, template_name, context)    

#def details(request, pk):
#    #course = Course.objects.get(pk=pk)
#    #caso não tenha valor retorna uma página http=404
#    course = get_object_or_404(Course, pk=pk)
#    context = {
#        'course': course
#    }
#    template_name = 'courses/details.html'
#    return render(request, template_name, context)

def details(request, slug):
    #course = Course.objects.get(pk=pk)
    #caso não tenha valor retorna uma página http=404
    course = get_object_or_404(Course, slug=slug)
    context = {}
    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid():
            context['is_valid'] = True # adiciona is_valid no contexto para ser utilizado no template
            #print(form.cleaned_data)
            #print(form.cleaned_data['name']) # para acessar um campo sempre com o dicionario cleaned_data. Retorna de acordo com o tipo.
            form = ContactCourse() # limpa o formulario
    else:
        form = ContactCourse()
    
    context['form'] = form
    context['course'] = course
    
    template_name = 'courses/details.html'
    return render(request, template_name, context)
    
    
@login_required
def enrollment(request, slug):
    course = get_object_or_404(Course, slug=slug)
    enrollment, created = Enrollment.objects.get_or_create(
            user=request.user,  # Filtro=Usuario que esta logado no sistema
            course=course     # Propriedade do model Enrollment
        )   # Este metodo retorna uma tupla. A inscrição(pega ou cria) e um bool
            # se foi criado ou nao
            
    if created:
        enrollment.active() # Metodo criado anteriormente
        messages.success(request, "Você foi inscrito no curso '%s' com sucesso." % course)
    else:
        messages.info(request, "Você ja está inscrito no curso '%s'." % course)
    
    #messages.add_message(request, messages.INFO, 'Hello world.')
    #from django.contrib.messages import get_messages
    #storage = get_messages(request)
    #for m in storage:
    #    print('========>',m)
    
    template_name = 'accounts/dashboard.html'
    return render(request, template_name)    
        
    

simplemooc/courses/templates/courses/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>
{{ message|linebreaks }}

simplemooc/courses/templates/courses/details.html
{% extends "base.html" %}

{% load static %}


{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {# devido ao metodo __str__() nao é necessario 'course.name' #}
                    {{ course }}
                </h1>
                <h2 class="splash-subhead">
                    {{ course.description }}
                </h2>
                <p>
                    <a href="{% url 'courses:enrollment' course.slug %}" class="pure-button primary-button">Inscreva-se</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead" style="position:relative;">Sobre o Curso</h4>
                {{ course.about|linebreaks }}
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            {% if course.image %}
                <img src="{{ course.image.url }}" alt="" style="width:240px;height:240px;" />
            {% else %}
                <img src="{% static 'img/course_default.png' %}" alt="" style="width:240px;height:240px;" />
            {% endif %}
            <h4>Dúvidas?</h4>
            <p>
                <a href="#contato" title="" class="pure-button">Fale Conosco</a>
            </p>
            
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon" id="contato">
    <div class="pure-u-1">
        <h3>Tire sua dúvida sobre o Curso</h3>
        {% if is_valid %}
            <p>Você enviou o formulário com sucesso</p>
        {% endif %}
        <form action="#contato" class="pure-form pure-form-aligned" method="post">
            {# proteção contra cross-site #}
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
{% comment %}
                    {# O bloco abaixo tambem pode ser substituido por {{ field.errors }} #}
                    {% if field.errors %}
                    <ul class="errorlist">
                        {% for error in field.errors %}
                        <li style="color:#C53F3F;">
                            {{ error }}
                        </li>
                        {% endfor %}
                    </ul>
                    {% endif %}
{% endcomment %}
                    {{ field.errors }}

                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>

{% endblock %}

simplemooc/courses/templates/courses/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <div class="l-box">
                <h4 class="content-subhead">Listagem dos cursos do Simple MOOC</h4>
                <p>Abaixo a lista dos cursos disponíveis na plantaforma</p>
            </div>
        </div>
    </div>
{% for course in courses %}
            <div class="pure-g-r content-ribbon">
                <div class="pure-u-1-2">
                    <div class="l-box">
                        <a href="{{ course.get_absolute_url }}">
                        {% if course.image %}
                        <img src="{{ course.image.url }}" alt="{{ course.name }}" height='250' width='250' />
                        {% else %}
                        <img src="{% static 'img/course_default.png' %}" alt="{{ course.name }}" height='250' width='250' />
                        {% endif %}
                        </a>
                    </div>
                </div>
                <div class="pure-u-1-3">
                    <div class="l-box">
                        <div class="l-box">
                            <h4 class="content-subhead">
                                <a href="{{ course.get_absolute_url }}" title="">{{ course.name }}</a>
                            </h4>
                            {{ course.description|linebreaks }}
                        </div>
                    </div>
                </div>
            </div>
{% empty %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <div class="l-box">
                <p>Nenhum curso disponíveis na plantaforma</p>
            </div>
        </div>
    </div>

{% endfor %}
{% endblock %}