simplemooc/accounts/urls.py
from django.conf.urls import  include, url
import simplemooc.accounts.views as views_accounts
from django.contrib.auth.views import logout_then_login
from django.contrib.auth.views import LoginView

# https://cursos.alura.com.br/forum/topico-login-django-1-10-46906
urlpatterns = [
    #url(r'^login/?$', login, kwargs={'template_name': 'accounts/login.html'}, name="login"),
    url(r'^$', views_accounts.dashboard, name='dashboard'),
    url(r'^register/$', views_accounts.register, name='register'),
    
    url(r'^password_reset/$', views_accounts.password_reset, name='password_reset'),
    
    url(r'^password_reset_confirm/(?P<key>\w+)/$', views_accounts.password_reset_confirm, name='password_reset_confirm'),
    
    url(r'^edit/$', views_accounts.edit, name='edit'),
    url(r'^edit_password/$', views_accounts.edit_password, name='edit_password'),
    url(r'^login/$', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    url(r'^logout/$',logout_then_login,{'login_url': 'accounts:login'}, name="logout"),
]

simplemooc/core/urls.py
from django.conf.urls import  include, url
from django.contrib import admin
admin.autodiscover()
import simplemooc.core.views

urlpatterns = [
    url(r'^$', simplemooc.core.views.home, name='home'),
    url(r'^contact/$',simplemooc.core.views.contact, name='contact'),
    url(r'^about/$',simplemooc.core.views.about, name='about'),
]


#urlpatterns = patterns('simplemooc.core.views',
#    url(r'^$','home', name='home'),
#    url(r'^contact/$','contact', name='contact'),
#    url(r'^about/$','about', name='about'),
#)

simplemooc/courses/urls.py
from django.conf.urls import  include, url
import simplemooc.courses.views

urlpatterns = [
    url(r'^$', simplemooc.courses.views.index, name='index'),
    #url(r'^(?P<pk>\d+)/$', simplemooc.courses.views.details, name='details'), # utilizará o codigo na url
    url(r'^(?P<slug>[\w_-]+)/$', simplemooc.courses.views.details, name='details'), # utlizara o slug, \w+ = 1 ou mais letras
    
    url(r'^(?P<slug>[\w_-]+)/enrollment/$', simplemooc.courses.views.enrollment, name='enrollment'),
]

simplemooc/urls.py
from django.conf.urls import include, url
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace='core')),
    url(r'^accounts/', include('simplemooc.accounts.urls', namespace='accounts')),
    url(r'^courses/', include('simplemooc.courses.urls', namespace='courses')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    #document_root=settings.MEDIA_ROOT = caminho absoluto
    #settings.MEDIA_URL = caminho relativo
    #este método funciona apenas de "debug mode"
    #indica qual é o caminho absoluto e relativo para estas midias
    #https://docs.djangoproject.com/en/dev/howto/static-files/
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/core/models.py
# -*- coding: utf 8 -*-
from django.db import models


    

simplemooc/core/views.py
from django.shortcuts import render
from django.http import HttpResponse
import sys

def home(request):
    return render(request, 'home.html')

def contact(request):
    return render(request, 'contact.html')

def about(request):
    return render(request, 'about.html')    

simplemooc/core/templates/about.html
{% extends "base.html" %}

{% block content %}
            <h2 class="content-subhead">About us</h2>
            <p>
                We are developers.
            </p>
{% endblock %}

simplemooc/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância.">
    <title>Simple MOOC</title>
    
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">
    
    <style media="screen" type="text/css">
        .footer {
            background: #111;
            color: #666;
            text-align: center;
            padding: 1em;
            font-size: 80%;
        }
        ul.errorlist {
            margin: 0;
            padding: 0;
        }
        ul.errorlist li {
            color: #C53F3F;display: block;margin: 0.3em 0;font-size: 0.9em;border: none;padding: 0;
        }
    </style>    
    

        <!--[if lte IE 8]>
            <link rel="stylesheet" href="css/layouts/side-menu-old-ie.css">
        <![endif]-->
        <!--[if gt IE 8]><!-->
            <link rel="stylesheet" href="{% static 'css/layouts/side-menu.css' %}">
        <!--<![endif]-->
</head>
<body>


<div id="layout">
    <!-- Menu toggle -->
    <a href="#menu" id="menuLink" class="menu-link">
        <!-- Hamburger icon -->
        <span></span>
    </a>

    <div id="menu">
        <div class="pure-menu">
            <a class="pure-menu-heading" href="{% url 'core:home' %}">Company</a>

            <ul class="pure-menu-list">
                {% if user.username %}
                    <li class="pure-menu-item" style='text-align: center;' ><strong>{{ user.username }}</strong></li>
                {% else %}
                    <li class="pure-menu-item" style='text-align: center;'><strong>anonymous</strong></li>
                {% endif %}
                <li class="pure-menu-item"><a href="{% url 'core:home' %}" class="pure-menu-link">Home</a></li>
                <li class="pure-menu-item"><a href="{% url 'courses:index' %}" class="pure-menu-link">Courses</a></li>
                <li class="pure-menu-item"><a href="{% url 'core:about' %}" class="pure-menu-link">About</a></li>
                <li class="pure-menu-item"><a href="{% url 'core:contact' %}" class="pure-menu-link">Contact</a></li>
                {% comment %}
                    https://stackoverflow.com/questions/17032174/having-trouble-with-user-is-authenticated-in-django-template
                {% endcomment %}
                {% if user.is_authenticated %}
                    <li class="pure-menu-item"><a href="{% url 'accounts:dashboard' %}" class="pure-menu-link">Dashboard</a></li>
                    <li class="pure-menu-item"><a href="{% url 'accounts:logout' %}" class="pure-menu-link">Logout</a></li>
                {% else %}
                    <li class="pure-menu-item"><a href="{% url 'accounts:login' %}" class="pure-menu-link">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>

    <div id="main">
        <div class="header">
            <h1>Uma simples plataforma de ensino a distância</h1>
            <h2>A subtitle for your page goes here</h2>
        </div>

        <div class="content">
            {% if messages %}
            <aside class="pure-u-1 ">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </aside>
            {% endif %}
            
            {% block content %}{% endblock %}
            
            <div class="footer">
                Simple MOOC - Uma simples plataforma de ensino a distância
            </div>
        </div>
    </div>
</div>




<script src="{% static 'js/ui.js' %}"></script>

</body>
</html>

simplemooc/core/templates/contact.html
{% extends "base.html" %}

{% block content %}
            <h2 class="content-subhead">Contact us</h2>
            <p>
                You can use this to contact us.
            </p>
{% endblock %}

simplemooc/core/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
            <h2 class="content-subhead">Now Let's Speak Some Latin</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>

            <div class="pure-g">
                <div class="pure-u-1-4">
                    <img class="pure-img-responsive" src="{% static 'img/course_default.png' %}" alt="Peyto Lake">
                </div>
                <div class="pure-u-1-4">
                    <img class="pure-img-responsive" src="http://farm3.staticflickr.com/2813/9069585985_80da8db54f.jpg" alt="Train">
                </div>
                <div class="pure-u-1-4">
                    <img class="pure-img-responsive" src="http://farm6.staticflickr.com/5456/9121446012_c1640e42d0.jpg" alt="T-Shirt Store">
                </div>
                <div class="pure-u-1-4">
                    <img class="pure-img-responsive" src="http://farm8.staticflickr.com/7357/9086701425_fda3024927.jpg" alt="Mountain">
                </div>
            </div>

            <h2 class="content-subhead">Try Resizing your Browser</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
{% endblock %}