simplemooc/accounts/urls.py
from django.conf.urls import  include, url
import simplemooc.accounts.views as views_accounts
from django.contrib.auth.views import logout_then_login
from django.contrib.auth.views import LoginView

# https://cursos.alura.com.br/forum/topico-login-django-1-10-46906
urlpatterns = [
    #url(r'^login/?$', login, kwargs={'template_name': 'accounts/login.html'}, name="login"),
    url(r'^$', views_accounts.dashboard, name='dashboard'),
    url(r'^register/$', views_accounts.register, name='register'),
    
    url(r'^password_reset/$', views_accounts.password_reset, name='password_reset'),
    
    url(r'^password_reset_confirm/(?P<key>\w+)/$', views_accounts.password_reset_confirm, name='password_reset_confirm'),
    
    url(r'^edit/$', views_accounts.edit, name='edit'),
    url(r'^edit_password/$', views_accounts.edit_password, name='edit_password'),
    url(r'^login/$', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    url(r'^logout/$',logout_then_login,{'login_url': 'accounts:login'}, name="logout"),
]

simplemooc/urls.py
from django.conf.urls import include, url
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace='core')),
    url(r'^accounts/', include('simplemooc.accounts.urls', namespace='accounts')),
    url(r'^courses/', include('simplemooc.courses.urls', namespace='courses')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    #document_root=settings.MEDIA_ROOT = caminho absoluto
    #settings.MEDIA_URL = caminho relativo
    #este método funciona apenas de "debug mode"
    #indica qual é o caminho absoluto e relativo para estas midias
    #https://docs.djangoproject.com/en/dev/howto/static-files/
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/accounts/models.py
from django.db import models
from django.core import validators
import re
from django.contrib.auth.models import (
    AbstractBaseUser, 
    PermissionsMixin,
    UserManager)
from django.conf import settings
    
# Aula: Custom user model
# Em settings deverá ser adicionado o AUTH_USER_MODEL para indicar este novo model
class User(AbstractBaseUser, PermissionsMixin):
    
    #Custom
    username = models.CharField(
        'Nome do Usuário', max_length=30, unique=True,
        validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'), 
        'Este campo apenas pode conter letras, digitos ou @.+-_', 'invalid')]
    )
    email = models.EmailField('E-mail', unique=True)
    name = models.CharField('Nome', max_length=100, blank=True)
    
    # Manter compatibilidade com o Admin
    # Ver https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#custom-users-and-the-built-in-auth-forms
    is_active = models.BooleanField('Está ativo?', blank=True, default=True)
    is_staff = models.BooleanField('É da equipe?', blank=True, default=False) # pode acessar a area admin
    
    # 'auto_now_add' tells Django that when you add a new row, you want the current date & time added. 
    # 'auto_now' tells Django to add the current date & time will be added EVERY time the record is saved.    
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)
    
    objects = UserManager()
    
    USERNAME_FIELD = 'username' # campo que vai ser a referencia no login e tb é unico
    REQUIRED_FIELDS = ['email'] # Utilizado na criação de superusuário.
    
    def __str__(self):                      # representação de string do usuário
        return self.name or self.username   # se nao tiver o name retorna o username
        
    def get_short_name(self):
        return self.username
        
    def get_full_name(self):
        return str(self) # metodo '__str__(self)' criado anteriormente
        
    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'
    
# Após isso vamos apagar o banco, recria-lo com o novo model, criar um uperuser
#>mv db.sqlite3 db.sqlite3.old
#>python manage.py makemigrations
#>python manage.py migrate
#>python manage.py showmigrations
# Nas versoes mis antigas do django "#>python manage.py syncdb"
#>python manage.py createsuperuser
#>sqlite3 db.sqlite3 
#sqlite> PRAGMA table_info(accounts_user); # ver as colunas da nova tabela
#sqlite> PRAGMA table_info(accounts_user); # ver o superuser criado


class PasswordReset(models.Model):
    
    # 'related_name' https://stackoverflow.com/questions/2642613/what-is-related-name-used-for-in-django
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Usuário',
        related_name='resets' # Se não for indicado o django cria o metodo passwordreset_set() (<model>_set())
        # from simplemooc.accounts.models import User
        # u = User.objects.all()[0]
        # u.resets.all() # if related_name is set
        # u.passwordreset_set.all()
    )
    
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    # O blank indica que este atributo não é obrigatori no caso da criação de um formulario
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True) 
    
    def __str__(self):
        return '{0} - {1}'.format(self.user, self.created_at)
        
    class Meta:
        verbose_name = 'Nova Senha'
        verbose_name_plural = 'Novas Senhas'
        ordering = ['-created_at']
        
        

simplemooc/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
#from django.contrib.auth.models import User # Model default do django

# Indicar o nosso custom user
# https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#referencing-the-user-model
from django.contrib.auth import get_user_model
User = get_user_model()

from simplemooc.core.mail import send_mail_template
from simplemooc.core.utils import generate_hash_key
from .models import PasswordReset

class PasswordResetForm(forms.Form):
    
    email = forms.EmailField(label='E-mail')
    
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError('Nenhum usuário encontrado com este email')
            
    def save(self):
        user = User.objects.get(email=self.cleaned_data['email'])
        key = generate_hash_key(user.username)
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = 'accounts/password_reset_mail.html'
        subject = 'Criar nova senha no Simple Mooc'
        context = {
            'reset': reset,
        }
        send_mail_template(subject, template_name, context, [user.email])

            
            

# Esta classe foi cirada para adicionar o campo email
# Ela extende a classe UserCreationForm e adiciona o amail
class RegisterForm(forms.ModelForm):
    
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmação de Senha', widget=forms.PasswordInput)
    

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('A confirmação não esta correta')
        return password2


    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1']) # set_password para criptografar a senha
        if commit:
            user.save()
        return user

    
    class Meta:
        model = User
        fields = ['username', 'email']
        
        
        
        
        
        
        
class EditAccountForm(forms.ModelForm): # ModelForm: formulario especifico do modelo. Pega os campos do modelo(model) e gera o formulario
    
    # Email unico no cadastro
    # from django.contrib.auth.models import User
    # Quando o djando faz a validação dos campos do form ele procura por metodos 'clean_<campo>'
    # Este metodo serve para testar, alterar ou extrair algo do campo email
    def clean_email(self):
        # instance: variavel do ModelForm que representa a instancia sendo alterada num determinado momento
        # Se não estiver sendo alterado entao o valor é 'none'
        email = self.cleaned_data['email']
        # filtra todos os usuários com email e exclui o usuário que esta sendo alterado
        queryset = User.objects.filter(
            email=email).exclude(pk=self.instance.pk)
        if queryset.exists():
            raise forms.ValidationError('Já existe usuário com este email')
        return email
        
    class Meta:
        model = User
        #fields = ['username', 'email', 'first_name', 'last_name'] # os campos do model (do django neste caso) que possam ser alterados
        fields = ['username', 'email', 'name']

simplemooc/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404 #  render adiciona a variaveis como context
from django.contrib.auth.forms import (UserCreationForm, PasswordChangeForm, SetPasswordForm) # modelform
from django.conf import settings
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib import messages

from simplemooc.core.utils import generate_hash_key
from simplemooc.courses.models import Enrollment

# Importa a classe criada RegisterForm onde foi adicionado o campo email
from .forms import RegisterForm, EditAccountForm, PasswordResetForm
from .models import PasswordReset


User = get_user_model()

# Template do painel do usuário (5:57)
# O decorator é uma função que será executada toda vez que a func dashboard for executado passando esta como parametro.
# Vai verificar se o usuario esta logado. 
#Se não estiver ele fará um redirect para a pagina de login colocando o parametro next
from django.contrib.auth.decorators import login_required
@login_required 
def dashboard(request):
    template_name = 'accounts/dashboard.html'
    context = {}
    #context['enrollments'] = Enrollment.objects.filter(user=request.user)
    return render(request, template_name, context)

@login_required
def edit(request):
    template_name = 'accounts/edit.html'
    context = {}
    if request.method == 'POST':
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(
                    request, 'Os dados da conta foram alterados com sucesso'
                )
            #form = EditAccountForm(instance=request.user)
            #context['success'] = True
    else:
        form = EditAccountForm(instance=request.user)
    context['form'] = form
    return render(request, template_name, context)



@login_required
def edit_password(request):
    template_name = 'accounts/edit_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            context['success'] = True
    else:
        form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)


# Override method get_context_data on class LoginView
# This assumes that the GET parameter will have the next url where user should be redirected in param next. 
# So, request should be of form localhost.com/login?next=/accounts/
# Este metodo foi sobrescrito para incluir a variavel next, que vem da url, no contexto
from django.contrib.auth.views import LoginView
from django.contrib.sites.shortcuts import get_current_site
def get_context_data(self, **kwargs):
    context = super(LoginView, self).get_context_data(**kwargs)
    context['next'] = self.request.REQUEST.get('next')
    current_site = get_current_site(self.request)
    context.update({
        self.redirect_field_name: self.get_redirect_url(),
        'site': current_site,
        'site_name': current_site.name,
    })
    if self.extra_context is not None:
        context.update(self.extra_context)
    return context

#def get_context_data(self, **kwargs):
#    context = super(LoginView, self).get_context_data(**kwargs)
#    context['next'] = self.request.REQUEST.get('next')
#    return context



# https://github.com/django/django/blob/master/django/contrib/auth/forms.py
def register(request):
    template_name = 'accounts/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        print(form)
        if form.is_valid():
            user = form.save()
            user1 = authenticate(
                    username=user.username,passowrd=form.cleaned_data['password1']
                )
            #login(request,user1)
            #print('====>',user.is_authenticated)
            #return redirect('core:home')
            return redirect(settings.LOGIN_URL)
    else:
        form = RegisterForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)
    
    
    
def password_reset(request):
    template_name = 'accounts/password_reset.html'
    context = {}
    form = PasswordResetForm(request.POST or None) # Se o POST estiver vazio então prenche com none. 
                                        # O mesmo que chamar PasswordResetForm() assim ele não é automaticamente validado
    if form.is_valid():
        form.save()
        context['sucess'] = True
    context['form'] = form
    return render(request, template_name, context)
    


def password_reset_confirm(request, key):
    template_name = 'accounts/password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)

simplemooc/accounts/templates/accounts/dashboard.html
{% extends "base.html" %}

<!--Procura por default na pasta templatetags -->
{% load courses_tags %}
<!--Tambem poderia de utilizado {# load simplemooc.courses.courses_tags #} -->

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb" style='list-style:none;'>
            {# http://django-bootstrap-breadcrumbs.readthedocs.io/en/latest/#breadcrumb-raw-safe #}
            {% block breadcrumb %}
            <li style='display:inline;'><a href="{% url 'accounts:dashboard' %}">Meu Painel</a></li>
            {% endblock %}
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <a class="pure-menu-heading">Meus Cursos</a>
            <ul>
                {% my_courses user %}
            </ul>
                <a class="pure-menu-heading">Minha Conta</a>
            <ul>
                <li><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>
                <li><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
            </ul>
        </div>
    </div>
    <div class="pure-u-1-4">
        <div class="inner">
            {% block dashboard_content %}
            <p><strong>Usuário</strong>: {{ user }}</p>
            <p><strong>E-mail</strong>: {{ user.email }}</p>
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/edit.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li style='display:inline;'>/</li>
    <li style='display:inline;'><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>Os dados foram alterados com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}            
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Salvar Modificações</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/accounts/templates/accounts/edit_password.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li style='display:inline;'>/</li>
    <li style='display:inline;'><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" novalidate method="post">
    {% csrf_token %}
    {% if success %}
    <p>A senha foi alterada com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Salvar nova senha.</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados de cadastro</h2>
        <form class="pure-form pure-form-stacked" novalidate role="form" action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                </div>
            </fieldset>
            <p>
                Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a> <br />
                Esqueceu a senha? <a href="{% url 'accounts:password_reset' %}" title="">Nova senha</a> <br />
            </p>
        </form>
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if sucess %}
        <p>Um email foi enviado para você com mais detalhes.</p>
        {% else %}
        <h2>Informe seu email</h2>
        <form class="pure-form pure-form-stacked" novalidate method="post">
            {% csrf_token %}
            <fieldset>
                {# Erros gerais #}
                {{ form.non_field_errors }}

                {# 'form' vem da view do django #}
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar E-mail</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
        <p>Sua senha foi criada com sucesso.</p>
        {% else %}
        <h2>Informe sua nova senha.</h2>
        <form class="pure-form pure-form-stacked" novalidate method="post">
            {% csrf_token %}
            <fieldset>
                {# Erros gerais #}
                {{ form.non_field_errors }}

                {# 'form' vem da view do django #}
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_mail.html
<!-- Este arquivo e apenas um html parcial para enviar no corpo do email -->
<!-- O objeto reset.key vem do contexto do form PasswordResetForm -->
<p>Para criar uma nova senha acesse o link <a href="https://simplemooc-leorzz.c9users.io{% url 'accounts:password_reset_confirm' reset.key %}" title="Link para criar nova senha">Criar nova senha</a></p>

simplemooc/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados</h2>
        <form class="pure-form pure-form-stacked" novalidate method="post">
            {% csrf_token %}
            <fieldset>
                {# Erros gerais #}
                {{ form.non_field_errors }}

                {# 'form' vem da view do django #}
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Registrar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}